### ISSUE TITLE
Strong gif game making for a pretty fly readme

### ISSUE THREAD

**Issue by HStewart23** [fac-15/chin#18]
Loving the gifs in your readme, a little humour goes a long way. The piping gif at the end is especially great. Just remember to update it with the stuff you did on Thursday and today so you can get credit for all your hard work !
![work gif](https://media.giphy.com/media/gmeJRdWDgQ3mw/giphy.gif)

**Comment by BenNewman90** [comment]
I agree. nice giffs but not enough of an explanation of what the project is.

**Comment by martinbagshaw** [comment]
WOOOOOOOOOOO! YEAH
![duff man](https://media0.giphy.com/media/3orieTfgp9ozOTv5wQ/giphy.gif?cid=3640f6095c014f2b4b75496f51beb087)
