### ISSUE TITLE
Use CodeCov or a similar tool to report and track test coverage.

### ISSUE THREAD

**Issue by HStewart23** [fac-15/chin#19]
This was also a goal for the project, this is possibly a stretch goal once you've done your tests !

![test gif](https://media.giphy.com/media/gw3IWyGkC0rsazTi/giphy.gif)

**Comment by arrested-developer** [comment]
If your team wants to set up Travis and CodeCov, I wrote [a guide](https://hackmd.io/LNg8wXcBTDSdShMTu64x5A) which might help:

**Comment by HStewart23** [comment]
*I found your tests! sorry got confused by the empty folder!  📂
